/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
  }
}

export function Sun(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Sun_1_1391000.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <Float speed={.4} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.None}
          rotation={[Math.PI / 2, 0, 0]}
          scale={30}
        />
      </Float>
    </group>
  )
}

useGLTF.preload('/Sun_1_1391000.glb')