/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef, type JSX } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Globe_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshPhysicalMaterial
  }
}

type ActionName = 'PlaneAction' | 'EmptyAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Earth(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/uploads_files_5973654_globe.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          visible={false}
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.004']}
          rotation={[0, 1.048, 0]}
          scale={[49.968, 22.802, 49.968]}
        />
        <group name="Empty">
          <mesh
            name="Globe_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.Globe_Material002_0.geometry}
            material={materials['Material.002']}
            position={[0, 9.472, 0]}
            rotation={[Math.PI * 0.5, Math.PI * 0, Math.PI * -0.082]}
            scale={8.263}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/uploads_files_5973654_globe.glb')
