/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useRef, type JSX } from 'react'
import { useGLTF, useAnimations, Float } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Globe_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshPhysicalMaterial
  }
}

type ActionName = 'PlaneAction' | 'EmptyAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>
interface Pos {pos: [x: number, y: number, z: number]}

function Eye({pos}: Pos) {
  return (
    <mesh position={pos} scale={[1, 1.4, .1]}>
      <torusGeometry args={[1, .2, 12, 48]}/>
      <meshToonMaterial color={'yellow'} />
    </mesh>
  )
}

function Smile() {
  return (
    <mesh rotation={[0, 0, Math.PI]} position={[0, 0, -10]}> {/* Rotate 180 degrees to flip it into a smile */}
      {/* args: [innerRadius, outerRadius, segments, phiSegments, thetaStart, thetaLength] */}
      <ringGeometry args={[1.8, 2, 32, 1, 0, Math.PI]} />
      <meshBasicMaterial color="black" side={THREE.DoubleSide} />
    </mesh>
  )
}


function Face(props: JSX.IntrinsicElements['group']) {
  return (
    <group {...props} >
      <Float rotationIntensity={0} floatingRange={[-.5, .5]}>
        <group>
          <Eye pos={[0, 0, 0]} />
          <Eye pos={[-4, 0, 0]} />
        </group>
        <Smile />
      </Float>
    </group>
  )
}

function Globe(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/uploads_files_5973654_globe.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props}>
      <group name="Scene">
        <mesh
          visible={false}
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.004']}
          rotation={[0, 1.048, 0]}
          scale={[49.968, 22.802, 49.968]}
        />
        <group name="Empty">
          <mesh
            name="Globe_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.Globe_Material002_0.geometry}
            material={materials['Material.002']}
            position={[0, 9.472, 0]}
            rotation={[Math.PI * 0.5, Math.PI * 0, Math.PI * -0.082]}
            scale={8.263}
          />
        </group>
      </group>
    </group>
  )
}

export function Earth(props: JSX.IntrinsicElements['group']) {
  return (
    <group {...props} dispose={null}>
      <Globe />
      <Face position={[0, 10, -10]}/>
    </group>
  )
}

useGLTF.preload('/uploads_files_5973654_globe.glb')
