/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { PlaneGeometry, type Group } from 'three'

export function Earth(props) {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF('/uploads_files_5973654_globe.glb')
  console.log(nodes)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.004']}
          rotation={[0, 1.048, 0]}
          scale={[49.968, 22.802, 49.968]}
        />
        <group name="Empty">
          <mesh
            name="Globe_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.Globe_Material002_0.geometry}
            material={materials['Material.002']}
            position={[0, 9.472, 0]}
            rotation={[2.759, -1.045, 2.852]}
            scale={8.263}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/uploads_files_5973654_globe.glb')